{% set name = "pyvideoreader" %}
{% set version = "0.5.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyvideoreader-{{ version }}.tar.gz
  sha256: 3a23f95dcda5047b5e38dceedbbeda0bec0f4be74674accfdb597a442d7641ff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - flit
    - pip
    - python {{ python_min }}
  run:
    - opencv
    - python >={{ python_min }}
    - setuptools

test:
  imports:
    - videoreader
  commands:
    - pip list
    - curl https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4 --output video.mp4
    - python -c "from videoreader import VideoReader;vr=VideoReader('video.mp4');print(vr);print(vr[100]);"
  requires:
    - curl
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/postpop/videoreader
  summary: Pythonic wrapper around opencv's VideoCapture().
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - postpop
