{% set name = "pyvideoreader" %}
{% set version = "0.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyvideoreader-{{ version }}.tar.gz
  sha256: 1ce2336ea121a2f3de2aca886efa525702c0c316782b933f480e371465eecaa8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit
    - pip
    - python >=3.6
  run:
    - opencv
    - python >=3.6
    - setuptools

test:
  imports:
    - videoreader
  commands:
    - pip list
    - curl https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4 --output video.mp4
    - python -c "from videoreader import VideoReader;vr=VideoReader('video.mp4');print(vr);print(vr[100]);"
  requires:
    - curl
    - pip

about:
  home: https://github.com/postpop/videoreader
  summary: Pythonic wrapper around opencv's VideoCapture().
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - postpop
